server:
  port: 8081
  servlet:
    context-path: /test
logging:
  level:
    com:
      example: debug
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
pagehelper:
  reasonable: true
devtools:
  livereload:
    enabled: true
    port: 35729
  restart:
    enabled: true
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    database: 1
    host: 127.0.0.1
    password: ''
    pool:
      max-active: 1000
      max-idle: 10
      max-wait: -1
      min-idle: 2
    port: 6379
    timeout: 0
  resources:
    add-mappings: false
  session:
    redis:
      namespace: evidence
    store-type: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/app?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root

